services:
  ssl-reminder:
    image: alpine:3.14
    container_name: ssl-reminder
    command: ["/home/app/ssl-reminder"]
    volumes:
      - ./dist/ssl-reminder:/home/app/ssl-reminder
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=veron.b@hsenidoutsourcing.com
      - SMTP_PASSWORD=************
      - HOST_ADDRESSES=logsiru-dev.practechs.com,logsilu.knsp.jp,pht-staging.practechs.com
      - MAIL_RECEIVERS=veron.b@hsenidoutsourcing.com
      - SSL_EXPIRE_CHECKER_CRON=* * * * *
      - REMINDER_DAYS_BEFORE_EXPIRATION=7