services:
  ssl-reminder:
    image: alpine:3.14
    container_name: ssl-reminder
    command: ["/home/app/ssl-reminder"]
    volumes:
      - ./dist/ssl-reminder:/home/app/ssl-reminder
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=veron.b@hsenidoutsourcing.com
      - SMTP_PASSWORD=gxfmuwgxhixanqbs
      - HOST_ADDRESSES=logsilu.knsp.jp,logsiru-dev.practechs.com
      - MAIL_RECEIVERS=veron.b@hsenidoutsourcing.com,harshana.k@hsenidoutsourcing.com
      - SSL_EXPIRE_CHECKER_CRON=0 */12 * * *
      - REMINDER_DAYS_BEFORE_EXPIRATION=7