name: publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.actor }}/${{ github.repository }}:${{ github.event.release.tag_name }} 

jobs:
  push_to_registry:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4

      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and tag image
        run: |
          DOCKER_BUILDKIT=1 docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_TAG }}

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_TAG }}